//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Script/HandMenu/XR Hand Menu.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @XRHandMenu : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @XRHandMenu()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""XR Hand Menu"",
    ""maps"": [
        {
            ""name"": ""UI"",
            ""id"": ""32f2129b-6ae3-431d-a308-34390ae9a16b"",
            ""actions"": [
                {
                    ""name"": ""Hand Menu"",
                    ""type"": ""Button"",
                    ""id"": ""f5d57636-dd83-4ec2-b632-c2fe4cdd8c42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""67801cb5-c89c-4ed1-9d37-0a307a86078f"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hand Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_HandMenu = m_UI.FindAction("Hand Menu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_HandMenu;
    public struct UIActions
    {
        private @XRHandMenu m_Wrapper;
        public UIActions(@XRHandMenu wrapper) { m_Wrapper = wrapper; }
        public InputAction @HandMenu => m_Wrapper.m_UI_HandMenu;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @HandMenu.started -= m_Wrapper.m_UIActionsCallbackInterface.OnHandMenu;
                @HandMenu.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnHandMenu;
                @HandMenu.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnHandMenu;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @HandMenu.started += instance.OnHandMenu;
                @HandMenu.performed += instance.OnHandMenu;
                @HandMenu.canceled += instance.OnHandMenu;
            }
        }
    }
    public UIActions @UI => new UIActions(this);
    public interface IUIActions
    {
        void OnHandMenu(InputAction.CallbackContext context);
    }
}
