//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/TestControlls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TestControlls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TestControlls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TestControlls"",
    ""maps"": [
        {
            ""name"": ""FirstPerson"",
            ""id"": ""740fe88d-24d2-459a-b509-dc1ec86df58a"",
            ""actions"": [
                {
                    ""name"": ""Forward"",
                    ""type"": ""Button"",
                    ""id"": ""9fbab8a6-9ad9-4469-ba47-adb28b37e59a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Backward"",
                    ""type"": ""Button"",
                    ""id"": ""62f15c85-4fed-4520-8d51-2f5020524e36"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseDeltaX"",
                    ""type"": ""Value"",
                    ""id"": ""30ef4017-df04-44c0-bae3-5e59d5a50ce8"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseDeltaY"",
                    ""type"": ""Value"",
                    ""id"": ""4df81516-12f4-4ab3-9f3b-4217daa44451"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1ee97319-f318-4e0e-828a-7fc13bb505ae"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7781200f-1b12-4a9b-a6eb-b98c9867c6dd"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Backward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d26c5d04-eb31-4fb5-bd83-b01b20f9ec0f"",
                    ""path"": ""<Mouse>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseDeltaX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88c1a7b4-947f-4c6e-ae61-ffd29a576db1"",
                    ""path"": ""<Mouse>/delta/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseDeltaY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // FirstPerson
        m_FirstPerson = asset.FindActionMap("FirstPerson", throwIfNotFound: true);
        m_FirstPerson_Forward = m_FirstPerson.FindAction("Forward", throwIfNotFound: true);
        m_FirstPerson_Backward = m_FirstPerson.FindAction("Backward", throwIfNotFound: true);
        m_FirstPerson_MouseDeltaX = m_FirstPerson.FindAction("MouseDeltaX", throwIfNotFound: true);
        m_FirstPerson_MouseDeltaY = m_FirstPerson.FindAction("MouseDeltaY", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // FirstPerson
    private readonly InputActionMap m_FirstPerson;
    private IFirstPersonActions m_FirstPersonActionsCallbackInterface;
    private readonly InputAction m_FirstPerson_Forward;
    private readonly InputAction m_FirstPerson_Backward;
    private readonly InputAction m_FirstPerson_MouseDeltaX;
    private readonly InputAction m_FirstPerson_MouseDeltaY;
    public struct FirstPersonActions
    {
        private @TestControlls m_Wrapper;
        public FirstPersonActions(@TestControlls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Forward => m_Wrapper.m_FirstPerson_Forward;
        public InputAction @Backward => m_Wrapper.m_FirstPerson_Backward;
        public InputAction @MouseDeltaX => m_Wrapper.m_FirstPerson_MouseDeltaX;
        public InputAction @MouseDeltaY => m_Wrapper.m_FirstPerson_MouseDeltaY;
        public InputActionMap Get() { return m_Wrapper.m_FirstPerson; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FirstPersonActions set) { return set.Get(); }
        public void SetCallbacks(IFirstPersonActions instance)
        {
            if (m_Wrapper.m_FirstPersonActionsCallbackInterface != null)
            {
                @Forward.started -= m_Wrapper.m_FirstPersonActionsCallbackInterface.OnForward;
                @Forward.performed -= m_Wrapper.m_FirstPersonActionsCallbackInterface.OnForward;
                @Forward.canceled -= m_Wrapper.m_FirstPersonActionsCallbackInterface.OnForward;
                @Backward.started -= m_Wrapper.m_FirstPersonActionsCallbackInterface.OnBackward;
                @Backward.performed -= m_Wrapper.m_FirstPersonActionsCallbackInterface.OnBackward;
                @Backward.canceled -= m_Wrapper.m_FirstPersonActionsCallbackInterface.OnBackward;
                @MouseDeltaX.started -= m_Wrapper.m_FirstPersonActionsCallbackInterface.OnMouseDeltaX;
                @MouseDeltaX.performed -= m_Wrapper.m_FirstPersonActionsCallbackInterface.OnMouseDeltaX;
                @MouseDeltaX.canceled -= m_Wrapper.m_FirstPersonActionsCallbackInterface.OnMouseDeltaX;
                @MouseDeltaY.started -= m_Wrapper.m_FirstPersonActionsCallbackInterface.OnMouseDeltaY;
                @MouseDeltaY.performed -= m_Wrapper.m_FirstPersonActionsCallbackInterface.OnMouseDeltaY;
                @MouseDeltaY.canceled -= m_Wrapper.m_FirstPersonActionsCallbackInterface.OnMouseDeltaY;
            }
            m_Wrapper.m_FirstPersonActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Forward.started += instance.OnForward;
                @Forward.performed += instance.OnForward;
                @Forward.canceled += instance.OnForward;
                @Backward.started += instance.OnBackward;
                @Backward.performed += instance.OnBackward;
                @Backward.canceled += instance.OnBackward;
                @MouseDeltaX.started += instance.OnMouseDeltaX;
                @MouseDeltaX.performed += instance.OnMouseDeltaX;
                @MouseDeltaX.canceled += instance.OnMouseDeltaX;
                @MouseDeltaY.started += instance.OnMouseDeltaY;
                @MouseDeltaY.performed += instance.OnMouseDeltaY;
                @MouseDeltaY.canceled += instance.OnMouseDeltaY;
            }
        }
    }
    public FirstPersonActions @FirstPerson => new FirstPersonActions(this);
    public interface IFirstPersonActions
    {
        void OnForward(InputAction.CallbackContext context);
        void OnBackward(InputAction.CallbackContext context);
        void OnMouseDeltaX(InputAction.CallbackContext context);
        void OnMouseDeltaY(InputAction.CallbackContext context);
    }
}
